### ISSUE TITLE
license

### ISSUE THREAD

**Issue by kjappelbaum** [numat/EQeq#3]
Hi 👋🏽 

i know that this is deprecated but there are a few active forks and for them it would be great to know the license. 
Could you maybe add a `LICENSE` file to this repository? Otherwise it is a bit unclear how/if one is allowed to reuse and share modified code. 

Thanks!

**Comment by patrickfuller** [comment]
@kjappelbaum updated!

I'd recommend using openbabel for this algorithm, as it's better implemented in their library.

**Comment by kjappelbaum** [comment]
Many thanks! We just made https://github.com/kjappelbaum/EQeq/tree/refactor which is pip installable as we faced issues with the implementation in openbabel (https://github.com/openbabel/openbabel/issues/2312)

**Comment by patrickfuller** [comment]
A PyPI install sounds great! If you're going to go down the path, I'd recommend cross-referencing the [openbabel implementation](https://github.com/openbabel/openbabel/blob/master/src/charges/eqeq.cpp) and editing the C. There are corner cases where the numat/EQeq version doesn't charge balance, and the openbabel version fixes those.

The openbabel version also requires a C dependency (boo) but runs ~4x faster than the numat/EQeq one.
